apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-zookeeper1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/data/zookeeper1"
    server: 192.168.5.196

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-zookeeper2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/data/zookeeper2"
    server: 192.168.5.196

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-zookeeper3
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/data/zookeeper3"
    server: 192.168.5.196
