apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat-guobbtest
  name: tomcat-guobbtest-deployment
  namespace: guobbtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-guobbtest-8080
  template:
    metadata:
      labels:
        app: tomcat-guobbtest-8080
    spec:
      containers:
      - name: nginx-ttt
        image: harbor.guobb.com/baseimages/tomcat:8.5.69
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - name: tomcat-apps
          mountPath: /usr/local/apache-tomcat-8.5.69/webapps/apps
      volumes:
      - name: tomcat-apps
        nfs:
          server: 192.168.5.196
          path: /data/apps
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat-guobbtest-service
  name: tomcat-guobbtest-spec
  namespace: guobbtest
spec:
  type: NodePort
  ports:
  - name: tomcat-8080
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 40003
  selector:
    app: tomcat-guobbtest-8080
